DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  id VARCHAR(20)  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  GENDER VARCHAR(20) NOT NULL,

);

INSERT INTO USER (id, NAME, GENDER) VALUES
 ('U1001','MARRY','FEMALE'),
 ('U1002','SALLY','FEMALE'),
 ('U1003','JOHN','MALE'),
 ('U1004','JIMM','MALE');